[2025-08-24 08:38:34,895: INFO: main: stage Data Ingestion stage initiated]
[2025-08-24 08:38:34,899: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-24 08:38:34,912: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-24 08:38:34,913: INFO: common: created directory at: artifacts]
[2025-08-24 08:38:34,914: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-24 08:38:38,841: INFO: data_ingestion: File is downloaded]
[2025-08-24 08:38:39,010: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 03:43:09,465: INFO: main: stage Data Ingestion stage initiated]
[2025-08-25 03:43:09,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 03:43:09,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 03:43:09,499: INFO: common: created directory at: artifacts]
[2025-08-25 03:43:09,500: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-25 03:43:09,501: INFO: data_ingestion: File already exits]
[2025-08-25 03:43:09,735: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 03:43:09,736: INFO: main: stage Data Transformation stage initiated]
[2025-08-25 03:43:09,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 03:43:09,743: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 03:43:09,744: INFO: common: created directory at: artifacts]
[2025-08-25 03:43:09,745: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-25 03:43:29,239: INFO: main: Stage Data Transformation stage Completed]
[2025-08-25 04:10:35,506: INFO: main: stage Data Ingestion stage initiated]
[2025-08-25 04:10:35,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:10:35,518: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:10:35,520: INFO: common: created directory at: artifacts]
[2025-08-25 04:10:35,521: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-25 04:10:35,521: INFO: data_ingestion: File already exits]
[2025-08-25 04:10:35,670: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 04:10:35,670: INFO: main: stage Data Transformation stage initiated]
[2025-08-25 04:10:35,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:10:35,675: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:10:35,676: INFO: common: created directory at: artifacts]
[2025-08-25 04:10:35,677: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-25 04:10:38,653: INFO: main: Stage Data Transformation stage Completed]
[2025-08-25 04:10:38,653: INFO: main: stage Model Trainer stage initiated]
[2025-08-25 04:10:38,657: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:10:38,659: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:10:38,661: INFO: common: created directory at: artifacts]
[2025-08-25 04:10:38,661: ERROR: main: 'ConfigurationManager' object has no attribute 'params']
Traceback (most recent call last):
  File "C:\Documents\python project\Text Summarization\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\config\configuration.py", line 44, in get_model_trainer_config
    params=self.params.TrainingArguments
           ^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'params'. Did you mean: 'paramss'?
[2025-08-25 04:11:30,546: INFO: main: stage Data Ingestion stage initiated]
[2025-08-25 04:11:30,549: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:11:30,572: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:11:30,573: INFO: common: created directory at: artifacts]
[2025-08-25 04:11:30,573: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-25 04:11:30,574: INFO: data_ingestion: File already exits]
[2025-08-25 04:11:30,697: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 04:11:30,698: INFO: main: stage Data Transformation stage initiated]
[2025-08-25 04:11:30,700: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:11:30,702: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:11:30,703: INFO: common: created directory at: artifacts]
[2025-08-25 04:11:30,703: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-25 04:11:33,655: INFO: main: Stage Data Transformation stage Completed]
[2025-08-25 04:11:33,655: INFO: main: stage Model Trainer stage initiated]
[2025-08-25 04:11:33,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:11:33,661: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:11:33,661: INFO: common: created directory at: artifacts]
[2025-08-25 04:11:33,662: ERROR: main: 'ConfigurationManager' object has no attribute 'params']
Traceback (most recent call last):
  File "C:\Documents\python project\Text Summarization\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\config\configuration.py", line 44, in get_model_trainer_config
    params=self.params.TrainingArguments
           ^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'params'. Did you mean: 'paramss'?
[2025-08-25 04:14:02,224: INFO: main: stage Data Ingestion stage initiated]
[2025-08-25 04:14:02,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:14:02,234: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:14:02,234: INFO: common: created directory at: artifacts]
[2025-08-25 04:14:02,235: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-25 04:14:02,235: INFO: data_ingestion: File already exits]
[2025-08-25 04:14:02,361: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 04:14:02,361: INFO: main: stage Data Transformation stage initiated]
[2025-08-25 04:14:02,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:14:02,367: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:14:02,367: INFO: common: created directory at: artifacts]
[2025-08-25 04:14:02,368: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-25 04:14:04,789: INFO: main: Stage Data Transformation stage Completed]
[2025-08-25 04:14:04,789: INFO: main: stage Model Trainer stage initiated]
[2025-08-25 04:14:04,792: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:14:04,795: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:14:04,795: INFO: common: created directory at: artifacts]
[2025-08-25 04:14:04,798: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-25 04:14:04,799: ERROR: main: "'ConfigBox' object has no attribute 'evaluation_strategy'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Documents\python project\Text Summarization\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\config\configuration.py", line 57, in get_model_trainer_config
    eval_strategy = params.evaluation_strategy,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'evaluation_strategy'"
[2025-08-25 04:15:46,333: INFO: main: stage Data Ingestion stage initiated]
[2025-08-25 04:15:46,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:15:46,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:15:46,340: INFO: common: created directory at: artifacts]
[2025-08-25 04:15:46,340: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-25 04:15:46,340: INFO: data_ingestion: File already exits]
[2025-08-25 04:15:46,457: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 04:15:46,457: INFO: main: stage Data Transformation stage initiated]
[2025-08-25 04:15:46,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:15:46,461: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:15:46,462: INFO: common: created directory at: artifacts]
[2025-08-25 04:15:46,462: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-25 04:15:48,688: INFO: main: Stage Data Transformation stage Completed]
[2025-08-25 04:15:48,689: INFO: main: stage Model Trainer stage initiated]
[2025-08-25 04:15:48,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:15:48,694: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:15:48,695: INFO: common: created directory at: artifacts]
[2025-08-25 04:15:48,696: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-25 04:15:48,696: ERROR: main: "'ConfigBox' object has no attribute 'evaluation_strategy'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Documents\python project\Text Summarization\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\config\configuration.py", line 58, in get_model_trainer_config
    eval_steps = params.evaluation_strategy,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'evaluation_strategy'"
[2025-08-25 04:16:48,345: INFO: main: stage Data Ingestion stage initiated]
[2025-08-25 04:16:48,349: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:16:48,353: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:16:48,353: INFO: common: created directory at: artifacts]
[2025-08-25 04:16:48,354: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-25 04:16:48,355: INFO: data_ingestion: File already exits]
[2025-08-25 04:16:48,474: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-25 04:16:48,475: INFO: main: stage Data Transformation stage initiated]
[2025-08-25 04:16:48,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:16:48,480: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:16:48,481: INFO: common: created directory at: artifacts]
[2025-08-25 04:16:48,482: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-25 04:16:50,786: INFO: main: Stage Data Transformation stage Completed]
[2025-08-25 04:16:50,786: INFO: main: stage Model Trainer stage initiated]
[2025-08-25 04:16:50,789: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-25 04:16:50,792: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-25 04:16:50,793: INFO: common: created directory at: artifacts]
[2025-08-25 04:16:50,793: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-25 04:16:50,794: ERROR: main: ModelTrainerConfig() takes no arguments]
Traceback (most recent call last):
  File "C:\Documents\python project\Text Summarization\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\config\configuration.py", line 48, in get_model_trainer_config
    model_trainer_config=ModelTrainerConfig(
        root_dir=config.root_dir,
    ...<10 lines>...
        gradient_accumulation_steps = params.gradient_accumulation_steps
    )
TypeError: ModelTrainerConfig() takes no arguments
[2025-08-26 05:08:27,819: INFO: main: stage Data Ingestion stage initiated]
[2025-08-26 05:08:27,824: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 05:08:27,829: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 05:08:27,831: INFO: common: created directory at: artifacts]
[2025-08-26 05:08:27,832: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-26 05:08:27,833: INFO: data_ingestion: File already exits]
[2025-08-26 05:08:28,005: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-26 05:08:28,005: INFO: main: stage Data Transformation stage initiated]
[2025-08-26 05:08:28,008: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 05:08:28,010: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 05:08:28,011: INFO: common: created directory at: artifacts]
[2025-08-26 05:08:28,011: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-26 05:08:30,790: INFO: main: Stage Data Transformation stage Completed]
[2025-08-26 05:08:30,791: INFO: main: stage Model Trainer stage initiated]
[2025-08-26 05:08:30,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 05:08:30,797: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 05:08:30,798: INFO: common: created directory at: artifacts]
[2025-08-26 05:08:30,799: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-26 05:08:30,799: ERROR: main: ModelTrainerConfig() takes no arguments]
Traceback (most recent call last):
  File "C:\Documents\python project\Text Summarization\main.py", line 34, in <module>
    model_trainer_pipeline.initiate_model_trainer()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Documents\python project\Text Summarization\src\textSummarizer\config\configuration.py", line 48, in get_model_trainer_config
    model_trainer_config=ModelTrainerConfig(
        root_dir=config.root_dir,
    ...<10 lines>...
        gradient_accumulation_steps = params.gradient_accumulation_steps
    )
TypeError: ModelTrainerConfig() takes no arguments
[2025-08-26 05:09:48,470: INFO: main: stage Data Ingestion stage initiated]
[2025-08-26 05:09:48,474: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 05:09:48,478: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 05:09:48,479: INFO: common: created directory at: artifacts]
[2025-08-26 05:09:48,479: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-26 05:09:48,480: INFO: data_ingestion: File already exits]
[2025-08-26 05:09:48,601: INFO: main: Stage Data Ingestion stage Completed]
[2025-08-26 05:09:48,601: INFO: main: stage Data Transformation stage initiated]
[2025-08-26 05:09:48,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 05:09:48,605: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 05:09:48,606: INFO: common: created directory at: artifacts]
[2025-08-26 05:09:48,606: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-26 05:09:51,198: INFO: main: Stage Data Transformation stage Completed]
[2025-08-26 05:09:51,199: INFO: main: *******************]
[2025-08-26 05:09:51,199: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-26 05:09:51,202: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 05:09:51,204: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 05:09:51,205: INFO: common: created directory at: artifacts]
[2025-08-26 05:09:51,206: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-26 05:21:15,302: INFO: rouge_scorer: Using default tokenizer.]
[2025-08-26 05:21:16,068: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-26 07:00:10,822: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 07:00:10,827: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 07:00:10,828: INFO: common: created directory at: artifacts]
[2025-08-26 07:00:10,830: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-26 07:04:28,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 07:04:28,418: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 07:04:28,419: INFO: common: created directory at: artifacts]
[2025-08-26 07:04:28,419: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-26 07:09:43,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 07:09:43,281: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 07:09:43,283: INFO: common: created directory at: artifacts]
[2025-08-26 07:09:43,283: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-26 07:16:03,508: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 07:16:03,516: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 07:16:03,520: INFO: common: created directory at: artifacts]
[2025-08-26 07:16:03,522: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-26 08:31:20,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-26 08:31:21,010: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-26 08:31:21,012: INFO: common: created directory at: artifacts]
[2025-08-26 08:31:21,013: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 02:37:05,397: ERROR: utils: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart
]
[2025-08-27 02:40:09,759: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 02:40:09,765: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 02:40:09,767: INFO: common: created directory at: artifacts]
[2025-08-27 02:40:09,768: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 02:40:09,770: ERROR: utils: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart
]
[2025-08-27 02:41:19,301: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 02:41:19,306: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 02:41:19,308: INFO: common: created directory at: artifacts]
[2025-08-27 02:41:19,308: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 02:43:02,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 02:43:02,081: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 02:43:02,082: INFO: common: created directory at: artifacts]
[2025-08-27 02:43:02,082: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 04:30:00,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 04:30:00,544: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 04:30:00,544: INFO: common: created directory at: artifacts]
[2025-08-27 04:30:00,545: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 05:10:06,093: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 05:10:06,099: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 05:10:06,101: INFO: common: created directory at: artifacts]
[2025-08-27 05:10:06,102: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 05:18:55,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 05:18:55,953: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 05:18:55,954: INFO: common: created directory at: artifacts]
[2025-08-27 05:18:55,955: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 05:22:37,683: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 05:22:37,688: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 05:22:37,688: INFO: common: created directory at: artifacts]
[2025-08-27 05:22:37,689: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 05:57:57,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 05:57:57,235: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 05:57:57,236: INFO: common: created directory at: artifacts]
[2025-08-27 05:57:57,237: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:03:33,757: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:03:33,762: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:03:33,763: INFO: common: created directory at: artifacts]
[2025-08-27 06:03:33,764: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:08:59,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:08:59,263: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:08:59,264: INFO: common: created directory at: artifacts]
[2025-08-27 06:08:59,265: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:11:49,723: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:11:49,728: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:11:49,729: INFO: common: created directory at: artifacts]
[2025-08-27 06:11:49,730: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:23:27,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:23:27,427: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:23:27,428: INFO: common: created directory at: artifacts]
[2025-08-27 06:23:27,428: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:28:05,458: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:28:05,463: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:28:05,464: INFO: common: created directory at: artifacts]
[2025-08-27 06:28:05,465: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:32:19,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:32:19,790: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:32:19,791: INFO: common: created directory at: artifacts]
[2025-08-27 06:32:19,792: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:41:46,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:41:46,616: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:41:46,617: INFO: common: created directory at: artifacts]
[2025-08-27 06:41:46,618: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 06:59:37,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 06:59:37,249: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 06:59:37,251: INFO: common: created directory at: artifacts]
[2025-08-27 06:59:37,252: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 07:09:25,792: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 07:09:25,796: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 07:09:25,798: INFO: common: created directory at: artifacts]
[2025-08-27 07:09:25,799: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 07:11:45,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 07:11:45,400: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 07:11:45,401: INFO: common: created directory at: artifacts]
[2025-08-27 07:11:45,402: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-27 09:10:56,508: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-27 09:10:56,522: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-27 09:10:56,524: INFO: common: created directory at: artifacts]
[2025-08-27 09:10:56,525: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-28 01:08:57,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-28 01:08:57,624: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-28 01:08:57,625: INFO: common: created directory at: artifacts]
[2025-08-28 01:08:57,627: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-28 02:02:16,311: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-28 02:02:16,316: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-28 02:02:16,317: INFO: common: created directory at: artifacts]
[2025-08-28 02:02:16,319: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-28 03:42:59,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-28 03:42:59,039: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-28 03:42:59,041: INFO: common: created directory at: artifacts]
[2025-08-28 03:42:59,041: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-29 03:30:07,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-29 03:30:07,377: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-29 03:30:07,378: INFO: common: created directory at: artifacts]
[2025-08-29 03:30:07,379: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-29 13:44:39,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-29 13:44:39,246: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-29 13:44:39,247: INFO: common: created directory at: artifacts]
[2025-08-29 13:44:39,247: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-29 13:44:39,250: ERROR: utils: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart
]
[2025-08-29 13:45:53,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-29 13:45:53,120: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-29 13:45:53,121: INFO: common: created directory at: artifacts]
[2025-08-29 13:45:53,122: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-29 20:33:56,193: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
[2025-08-29 20:46:13,209: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
[2025-08-29 20:46:51,609: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
[2025-08-29 20:49:50,145: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
